[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
python = ">=3.11,<4.0"
gen = { path = "." }

[pypi-dependencies]
jax = ">=0.4.24, <0.4.38"
tensorflow-probability = ">=0.23.0"
jaxtyping = ">=0.2.24"
beartype = ">=0.20.0"
deprecated = ">=1.2.14"
penzai = ">=0.0.1"
treescope = ">=0.1.5"
numpy = ">=1.22,<2.0.0"
genstudio = ">=2025.2.1"
genjax = ">=0.0.0"

[package]
name = "gen"
version = "0.0.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"
python = ">=3.11,<4.0"

[package.run-dependencies]
numpy = "<2.0.0"