name: Codebase tests

on:
  pull_request:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  XLA_FLAGS: --xla_gpu_enable_command_buffer=
  XLA_PYTHON_CLIENT_PREALLOCATE: false
  XLA_PYTHON_CLIENT_ALLOCATOR: platform

jobs:
  test:
    strategy:
      matrix:
        runner: [ubuntu-22.04, ParallelHoss]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: install curl
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: curl
          version: 1.0

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          source ~/.bashrc
          export PATH=$HOME/.pixi/bin
          ls -la
          cd packages/genjax
          pixi run -e gpu-dev tests
          pixi run -e cpu-dev tests
