name: Codebase tests

on:
  pull_request:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  XLA_FLAGS: --xla_gpu_enable_command_buffer=
  XLA_PYTHON_CLIENT_PREALLOCATE: false
  XLA_PYTHON_CLIENT_ALLOCATOR: platform

jobs:
  test:
    strategy:
      matrix:
        runner: [ParallelHoss]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          environments: >- 
            cpu-dev
            gpu-dev

      - run: |
          cd ~/genjax/packages/genjax
          pixi run -e gpu-dev tests
          pixi run -e cpu-dev tests
